version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:5.0.16-ubi8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerceApi
    volumes:
      - mongodb_data:/data/db 
volumes:
  mongodb_data: